/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LineSetupRouteImport } from './routes/line-setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SsoAuthorizeRouteImport } from './routes/sso.authorize'
import { Route as ApiPublicSsoExchangeRouteImport } from './routes/api/public/sso/exchange'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LineSetupRoute = LineSetupRouteImport.update({
  id: '/line-setup',
  path: '/line-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoAuthorizeRoute = SsoAuthorizeRouteImport.update({
  id: '/sso/authorize',
  path: '/sso/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSsoExchangeRoute = ApiPublicSsoExchangeRouteImport.update({
  id: '/api/public/sso/exchange',
  path: '/api/public/sso/exchange',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/docs': typeof DocsRoute
  '/line-setup': typeof LineSetupRoute
  '/settings': typeof SettingsRoute
  '/sso/authorize': typeof SsoAuthorizeRoute
  '/api/public/sso/exchange': typeof ApiPublicSsoExchangeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/docs': typeof DocsRoute
  '/line-setup': typeof LineSetupRoute
  '/settings': typeof SettingsRoute
  '/sso/authorize': typeof SsoAuthorizeRoute
  '/api/public/sso/exchange': typeof ApiPublicSsoExchangeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/docs': typeof DocsRoute
  '/line-setup': typeof LineSetupRoute
  '/settings': typeof SettingsRoute
  '/sso/authorize': typeof SsoAuthorizeRoute
  '/api/public/sso/exchange': typeof ApiPublicSsoExchangeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/business'
    | '/docs'
    | '/line-setup'
    | '/settings'
    | '/sso/authorize'
    | '/api/public/sso/exchange'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/business'
    | '/docs'
    | '/line-setup'
    | '/settings'
    | '/sso/authorize'
    | '/api/public/sso/exchange'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/business'
    | '/docs'
    | '/line-setup'
    | '/settings'
    | '/sso/authorize'
    | '/api/public/sso/exchange'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BusinessRoute: typeof BusinessRoute
  DocsRoute: typeof DocsRoute
  LineSetupRoute: typeof LineSetupRoute
  SettingsRoute: typeof SettingsRoute
  SsoAuthorizeRoute: typeof SsoAuthorizeRoute
  ApiPublicSsoExchangeRoute: typeof ApiPublicSsoExchangeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line-setup': {
      id: '/line-setup'
      path: '/line-setup'
      fullPath: '/line-setup'
      preLoaderRoute: typeof LineSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso/authorize': {
      id: '/sso/authorize'
      path: '/sso/authorize'
      fullPath: '/sso/authorize'
      preLoaderRoute: typeof SsoAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sso/exchange': {
      id: '/api/public/sso/exchange'
      path: '/api/public/sso/exchange'
      fullPath: '/api/public/sso/exchange'
      preLoaderRoute: typeof ApiPublicSsoExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BusinessRoute: BusinessRoute,
  DocsRoute: DocsRoute,
  LineSetupRoute: LineSetupRoute,
  SettingsRoute: SettingsRoute,
  SsoAuthorizeRoute: SsoAuthorizeRoute,
  ApiPublicSsoExchangeRoute: ApiPublicSsoExchangeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
